# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Tensor
tagline:          'A C++ expression template library for N dimensional tensor computations'
description:      'A C++ expression template library designed to provide operations on N dimensional tensors using static or dynamic containers, and CPU or GPU devices.'
url:              https://robclu.github.io/tensor
baseurl:          /tensor

author:
  name:           'Rob Clucas'
  url:              https://robclu.github.io/tensor

paginate:         5

# Custom vars
version:          1.0

github:
  repo:          https://github.com/robclu/tensor
